export const datasets = [
  [
    { a: 1, b: 2, c: 3, d: 2, e: 3.2, color: 'red' },
    { a: 2, b: 1.1, c: 1, d: 2, e: 2.3, color: 'blue' },
    { a: 2, b: 1, c: 1, d: 3.3, e: 5, color: 'yellow' },
    { a: 2.7, b: 2.4, c: 5, d: 4, e: 2, color: 'orange' },
    { a: 1.9, b: 2.3, c: 4.1, d: 1.3, e: 4.1, color: 'green' },
  ],
  [
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'red',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'blue',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'yellow',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'orange',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'green',
    },
  ],
  [
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'red',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'blue',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'yellow',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'orange',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'green',
    },
  ],
  [
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'red',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'blue',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'yellow',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'orange',
    },
    {
      a: Math.random() * 5,
      b: Math.random() * 5,
      c: Math.random() * 5,
      d: Math.random() * 5,
      e: Math.random() * 5,
      color: 'green',
    },
  ],
];
