export const datasets = [
  [
    {
      agility: 1,
      strength: 2,
      durability: 3,
      luck: 2,
      speech: 3.2,
      color: '#b04848',
      label: 'Emma',
    },
    {
      agility: 3,
      strength: 1.1,
      durability: 1,
      luck: 2,
      speech: 2.3,
      color: '#5387e0',
      label: 'Greg',
    },
    {
      agility: 2,
      strength: 1,
      durability: 1,
      luck: 3.3,
      speech: 5,
      color: '#dbd33b',
      label: 'Hannah',
    },
  ],
  [
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#b04848',
      label: 'Emma',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#5387e0',
      label: 'Greg',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#dbd33b',
      label: 'Hannah',
    },
  ],
  [
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#b04848',
      label: 'Emma',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#5387e0',
      label: 'Greg',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#dbd33b',
      label: 'Hannah',
    },
  ],
  [
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#b04848',
      label: 'Emma',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#5387e0',
      label: 'Greg',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: '#dbd33b',
      label: 'Hannah',
    },
  ],
];
