export const datasets = [
  [
    {
      agility: 1,
      strength: 2,
      durability: 3,
      luck: 2,
      speech: 3.2,
      color: 'red',
    },
    {
      agility: 2,
      strength: 1.1,
      durability: 1,
      luck: 2,
      speech: 2.3,
      color: 'blue',
    },
    {
      agility: 2,
      strength: 1,
      durability: 1,
      luck: 3.3,
      speech: 5,
      color: 'yellow',
    },
    {
      agility: 2.7,
      strength: 2.4,
      durability: 5,
      luck: 4,
      speech: 2,
      color: 'orange',
    },
    {
      agility: 1.9,
      strength: 2.3,
      durability: 4.1,
      luck: 1.3,
      speech: 4.1,
      color: 'green',
    },
  ],
  [
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'red',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'blue',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'yellow',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'orange',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'green',
    },
  ],
  [
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'red',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'blue',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'yellow',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'orange',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'green',
    },
  ],
  [
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'red',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'blue',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'yellow',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'orange',
    },
    {
      agility: Math.random() * 5,
      strength: Math.random() * 5,
      durability: Math.random() * 5,
      luck: Math.random() * 5,
      speech: Math.random() * 5,
      color: 'green',
    },
  ],
];
